import './globals.css'
import { Inter } from 'next/font/google'
import React from 'react';
import {Navbar} from '../components';
import { Footer } from '@/container';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Gerich Restaurant',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <Navbar />
        {children}
        <Footer/>
        </main>
        
        </body>
    </html>
  )
}
